include:
    - compose-database.yaml

services:

    backend:
        container_name: spring
        build:
            context: ./ # Use root context so Dockerfile can copy /src folder and /pom.xml file
            dockerfile: ./infra/spring/Dockerfile
        ports:
            - '${SERVER_PORT:-8080}:8080'
        depends_on:
            postgresql: # Service declared on compose-database.yaml file
                condition: service_healthy
